# Generated by Django 3.2.12 on 2022-03-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tv_name',
            field=models.CharField(max_length=3),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('tv_name',), name='teams_team_tv_name_unique'),
        ),
    ]
