# Generated by Django 3.2.12 on 2022-04-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tv_name_without_unique',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('tv_name_without_unique',), name='teams_team_tv_name_unique'),
        ),
    ]
