# Generated by Django 3.2.12 on 2022-04-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20220410_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name_with_index',
            field=models.CharField(db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
