# Generated by Django 3.2.12 on 2022-04-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_name_with_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='city_with_partial_index',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(condition=models.Q(('city_with_partial_index', "Zora's Domain")), fields=['city_with_partial_index'], name='teams_team_city_zora'),
        ),
    ]
