# Generated by Django 3.2.12 on 2022-05-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20220520_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='grammy_nominated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='grammy_nominated',
            field=models.BooleanField(default=False),
        ),
    ]
